### ISSUE TITLE
There is no correct way how to style the inner editor container

### ISSUE THREAD

**Issue by jhrdina** [LostInBrittany/ace-widget#6]
You cannot easily get rid of the default grey border or style the inner editor in any way.

There should be a mixin that would allow user customize the appearance.

e.g.:

``` css
#editor {
  border: 1px solid #e3e3e3;
  border-radius: 4px;
  @apply(--ace-widget-editor);
}
```
